version: '3'

services:
  aps_wordpress:
    image: wordpress:5.9-php8.1-fpm-alpine
    container_name: aps-wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=${MYSQL_HOST}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DB}
    volumes:
      - ./conf/php:/usr/local/etc/php-fpm.d
      - wordpress:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins
      - ./themes/bvs-aps:/var/www/html/wp-content/themes/bvs-aps
    deploy:
      resources:
        limits:
          memory: ${MEMORY_WORDPRESS_LIMIT}
        reservations:
          memory: ${MEMORY_WORDPRESS_RESERVATION}

    networks:
      - nginx-proxy

  aps_webserver:
    depends_on:
      - aps_wordpress
    image: nginx:1.20-alpine
    container_name: aps-webserver
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${LOG_PATH}:/var/log/nginx
      - wordpress:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins
      - ./themes/bvs-aps:/var/www/html/wp-content/themes/bvs-aps
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
    deploy:
      resources:
        limits:
          memory: ${MEMORY_WEBSERVER_LIMIT}
        reservations:
          memory: ${MEMORY_WEBSERVER_RESERVATION}

    networks:
      - nginx-proxy


volumes:
  wordpress:

networks:
  nginx-proxy:
      external: true
