version: '3'

services:
  # aps_db:
  #   image: mysql:8.0
  #   container_name: aps-db
  #   restart: unless-stopped
  #   env_file: .env
  #   environment:
  #     - MYSQL_DATABASE=wordpress_aps
  #   volumes:
  #     - dbdata:/var/lib/mysql
  #   command: '--default-authentication-plugin=mysql_native_password'
  #   networks:
  #     - nginx-proxy

  aps_wordpress:
    # depends_on:
    #   - aps_db
    image: wordpress:5.9-php8.1-fpm-alpine
    container_name: aps-wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=${MYSQL_HOST}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DB}
    volumes:
      - ./conf/php:/usr/local/etc/php-fpm.d
      - wordpress:/var/www/html
      - ./themes/bvs-aps:/var/www/html/wp-content/themes/bvs-aps
    networks:
      - nginx-proxy

  aps_webserver:
    depends_on:
      - aps_wordpress
    image: nginx:1.20-alpine
    container_name: aps-webserver
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - wordpress:/var/www/html
      - ./themes/bvs-aps:/var/www/html/wp-content/themes/bvs-aps
      - ${LOG_PATH}:/var/log/nginx
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
    networks:
      - nginx-proxy


volumes:
  wordpress:
  dbdata:

networks:
  nginx-proxy:
      external: true
